
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class EmpalizadaWestAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {545, 0, 0, 0}, {545, 0, 1, 0}, {545, 0, 2, 0}// 1	2	3	
			, {545, 0, -1, 0}, {545, 0, 0, 10}, {545, 0, 2, 10}// 4	5	6	
			, {1285, 1, -1, 12}, {1285, 1, 0, 12}, {1285, 1, 1, 12}// 7	8	9	
			, {1285, 1, 2, 12}, {4014, 1, 2, 0}, {4014, 1, 2, 3}// 10	11	12	
			, {4014, 1, 2, 6}, {4014, 1, 2, 9}, {4014, 1, -1, 0}// 13	14	15	
			, {4014, 1, -1, 3}, {4014, 1, -1, 6}, {4014, 1, -1, 9}// 16	17	18	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new EmpalizadaWestAddonDeed();
			}
		}

		[ Constructable ]
		public EmpalizadaWestAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public EmpalizadaWestAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class EmpalizadaWestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new EmpalizadaWestAddon();
			}
		}

		[Constructable]
		public EmpalizadaWestAddonDeed()
		{
			Name = "EmpalizadaWest";
		}

		public EmpalizadaWestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}