
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;
using Server.Engines.XmlSpawner2;

namespace Server.Items
{
	public class EmpalizadaPuertaNAddon : BaseAddon
	{
         private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {546, -2, -1, 9}, {545, -1, 0, 0}, {2172, -1, 0, 9}// 1	2	4	
			, {2172, -1, 0, 16}, {2172, -1, 0, 14}, {1220, 0, 0, 24}// 5	6	7	
			, {1220, 1, 0, 24}, {2172, -1, 0, 18}, {546, -1, -1, 2}// 8	9	10	
			, {1220, -2, 0, 12}, {2172, -2, 0, 13}, {546, -1, -1, 15}// 11	12	13	
			, {546, -2, -1, 2}, {546, 1, -1, 23}, {546, 0, -1, 23}// 14	15	16	
			, {1848, -3, 0, 2}, {1848, -3, 0, 7}, {546, -3, -1, 2}// 17	18	19	
			, {546, -1, 1, 2}, {2171, -2, 1, 2}, {2171, -2, 1, 4}// 20	21	23	
			, {2171, -2, 1, 8}, {2171, -2, 2, 2}, {545, -1, 1, 2}// 24	25	26	
			, {2171, -2, 1, 6}, {546, 3, -1, 12}, {2170, 2, 0, 16}// 27	28	29	
			, {546, 2, -1, 18}, {546, 3, -1, 2}, {1220, 3, 0, 12}// 30	31	32	
			, {555, 3, 0, 6}, {546, 2, -1, 2}, {2170, 2, 0, 18}// 33	34	35	
			, {2170, 2, 0, 12}, {2170, 2, 0, 14}, {2170, 3, 0, 12}// 36	37	38	
			, {555, 3, 0, 2}, {1848, 4, 0, 2}, {1848, 4, 0, 7}// 39	40	41	
			, {546, 4, -1, 2}, {2171, 3, 1, 8}, {546, 2, 1, 2}// 42	43	44	
			, {2171, 3, 1, 6}, {2171, 3, 2, 2}, {2171, 3, 1, 2}// 45	47	48	
			, {2171, 3, 1, 4}, {545, 2, 1, 2}// 49	50	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new EmpalizadaPuertaNAddonDeed();
			}
		}

		[ Constructable ]
		public EmpalizadaPuertaNAddon()
		{
			  XmlAttach.AttachTo(this, new XmlCitySiege(3500,60,60,1,1,5)); //<-------new CitySiege Attachment


            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			
			
			AddComplexComponent( (BaseAddon) this, 2567, 0, 0, 17, 0, 8, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 2572, -1, 2, 19, 0, 5, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 2572, 2, 2, 19, 0, 5, "", 1);// 46
		}

		public EmpalizadaPuertaNAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class EmpalizadaPuertaNAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new EmpalizadaPuertaNAddon();
			}
		}

		[Constructable]
		public EmpalizadaPuertaNAddonDeed()
		{
			Name = "EmpalizadaPuertaN";
		}

		public EmpalizadaPuertaNAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}