
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;
using Server.Engines.XmlSpawner2;

namespace Server.Items
{
	public class EmpalizadaEscaleraWestAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {545, -1, 0, 2}, {545, -1, 1, 2}, {545, -1, 2, 2}// 1	2	3	
			, {545, -1, -1, 2}, {545, -1, 0, 12}, {545, -1, 2, 12}// 4	5	6	
			, {1285, 0, -1, 14}, {1285, 0, 0, 14}, {1285, 0, 1, 14}// 7	8	9	
			, {1285, 0, 2, 14}, {2202, 2, 0, 0}, {2202, 1, 0, 6}// 10	11	12	
			, {4014, 0, 2, 2}, {4014, 0, 2, 5}, {4014, 0, 2, 8}// 13	14	15	
			, {4014, 0, 2, 11}, {4014, 0, -1, 2}, {4014, 0, -1, 5}// 16	17	18	
			, {4014, 0, -1, 8}, {4014, 0, -1, 11}// 19	20	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new EmpalizadaEscaleraWestAddonDeed();
			}
		}

		[ Constructable ]
		public EmpalizadaEscaleraWestAddon()
		{
			  XmlAttach.AttachTo(this, new XmlCitySiege(2500,60,60,1,1,5)); //<-------new CitySiege Attachment


            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public EmpalizadaEscaleraWestAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class EmpalizadaEscaleraWestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new EmpalizadaEscaleraWestAddon();
			}
		}

		[Constructable]
		public EmpalizadaEscaleraWestAddonDeed()
		{
			Name = "EmpalizadaEscaleraWest";
		}

		public EmpalizadaEscaleraWestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}