
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;
using Server.Engines.XmlSpawner2;

namespace Server.Items
{
	public class EmpalizadaEscaleraEstAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {545, 1, -1, 2}, {1288, 0, 0, 12}, {545, 1, 0, 12}// 1	2	3	
			, {545, 1, 0, 2}, {545, 1, 1, 2}, {1288, 0, -1, 12}// 4	5	6	
			, {1288, 0, 1, 12}, {1288, -1, -1, 12}, {2204, -1, 0, 6}// 7	8	9	
			, {2204, -1, 1, 0}, {545, 1, 2, 2}, {545, 1, 2, 12}// 10	11	12	
			, {1288, 0, 2, 12}, {547, 1, 2, 2}// 13	14	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new EmpalizadaEscaleraEstAddonDeed();
			}
		}

		[ Constructable ]
		public EmpalizadaEscaleraEstAddon()
		{
  XmlAttach.AttachTo(this, new XmlCitySiege(2500,60,60,1,1,5)); //<-------new CitySiege Attachment

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public EmpalizadaEscaleraEstAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class EmpalizadaEscaleraEstAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new EmpalizadaEscaleraEstAddon();
			}
		}

		[Constructable]
		public EmpalizadaEscaleraEstAddonDeed()
		{
			Name = "EmpalizadaEscalerasEst";
		}

		public EmpalizadaEscaleraEstAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}