
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;
using Server.Engines.XmlSpawner2;

namespace Server.Items
{
	public class EmpalizadaPuertaWestAddon : BaseAddon
	{
         private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {1848, 0, 3, 5}, {554, 0, -2, 4}, {554, 0, 1, 8}// 1	2	3	
			, {554, 0, 1, 4}, {554, 0, 1, 0}, {554, 0, 1, 0}// 4	5	6	
			, {554, 0, 1, 0}, {2173, 0, -2, 10}, {545, -1, -2, 0}// 8	9	10	
			, {2170, 1, 3, 5}, {545, -1, 0, 16}, {2170, 2, -3, 0}// 11	12	13	
			, {545, -1, 1, 16}, {545, -1, 2, 11}, {546, 1, -2, 0}// 14	15	17	
			, {547, 1, 2, 0}, {545, -1, 2, 0}, {545, 1, -1, 0}// 18	19	21	
			, {545, -1, -2, 8}, {545, -1, -1, 16}, {2170, 1, -3, 5}// 22	23	24	
			, {554, 0, -2, 0}, {1848, 0, -3, 5}, {2171, 0, 2, 10}// 25	26	27	
			, {545, -1, -3, 0}, {545, -1, 3, 2}, {554, 0, -2, 8}// 28	29	30	
			, {1848, 1, -3, 0}, {1848, 0, -3, 0}, {1288, 0, -1, 16}// 31	32	33	
			, {1288, 0, 0, 16}, {1288, 0, 1, 16}, {1848, 0, 3, 0}// 34	35	36	
			, {1848, 1, 3, 0}, {2170, 2, 3, 0}, {1848, 0, -4, 0}// 37	38	39	
			, {1848, 0, -4, 5}, {1848, 0, 4, 0}, {1848, 0, 4, 5}// 40	41	42	
			, {545, -1, 4, 0}, {545, -1, -4, 0}// 43	44	
		};
 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new EmpalizadaPuertaWestAddonDeed();
			}
		}

		[ Constructable ]
		public EmpalizadaPuertaWestAddon()
		{
									  XmlAttach.AttachTo(this, new XmlCitySiege(3500,60,60,1,1,5)); //<-------new CitySiege Attachment


            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2567, 2, 2, 15, 0, 8, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 2567, 2, -1, 15, 0, 8, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 2572, 0, -1, 10, 0, 5, "", 1);// 40

		}

		public EmpalizadaPuertaWestAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class EmpalizadaPuertaWestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new EmpalizadaPuertaWestAddon();
			}
		}

		[Constructable]
		public EmpalizadaPuertaWestAddonDeed()
		{
			Name = "EmpalizadaPuertaWest";
		}

		public EmpalizadaPuertaWestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}