
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;
using Server.Engines.XmlSpawner2;

namespace Server.Items
{
	public class EmpalizadaEstAddon : BaseAddon
	{
          private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {545, 1, -1, 0}, {1288, 0, 0, 10}, {545, 1, 0, 10}// 1	2	3	
			, {545, 1, 0, 0}, {545, 1, 1, 0}, {1288, 0, -1, 10}// 4	5	6	
			, {1288, 0, 1, 10}, {545, 1, 2, 0}, {545, 1, 2, 10}// 7	8	9	
			, {1288, 0, 2, 10}, {547, 1, 2, 0}// 10	11	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new EmpalizadaEstAddonDeed();
			}
		}

		[ Constructable ]
		public EmpalizadaEstAddon()
		{
  XmlAttach.AttachTo(this, new XmlCitySiege(2500,60,60,1,1,5)); //<-------new CitySiege Attachment

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public EmpalizadaEstAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class EmpalizadaEstAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new EmpalizadaEstAddon();
			}
		}

		[Constructable]
		public EmpalizadaEstAddonDeed()
		{
			Name = "EmpalizadaEst";
		}

		public EmpalizadaEstAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}