/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;
using Server.Regions;
using Server.Engines.XmlSpawner2;

namespace Server.Items
{
	public class BarracksAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				//return new BarracksAddonDeed();
                                return null;
			}
		}

		[ Constructable ]
		public BarracksAddon()
		{
  //add a siege attachment with 500 hits, 60% fire resistance, 20% physical resistance
                XmlAttach.AttachTo(this, new XmlCitySiege(5000,60,60,1,1,5)); //<-------new CitySiege Attachment
			AddonComponent ac;
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -3, -2, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -3, -1, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -3, 0, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -3, 1, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -3, 2, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -3, 3, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -2, -2, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -2, -1, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -2, 0, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -2, 1, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -2, 2, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -2, 3, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -1, -2, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -1, -1, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -1, 0, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -1, 1, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -1, 2, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -1, 3, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 0, -2, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 0, -1, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 0, 0, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 0, 1, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 0, 2, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 0, 3, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 1, -2, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 1, -1, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 1, 0, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 1, 1, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 1, 2, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 1, 3, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 2, -2, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 2, -1, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 2, 0, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 2, 1, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 2, 2, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 2, 3, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 2, -3, 7 );
			ac = new AddonComponent( 3284 );
			AddComponent( ac, -7, -3, 7 );
			ac = new AddonComponent( 3317 );
			AddComponent( ac, -5, -4, 7 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, -4, -4, 33 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, -4, -4, 30 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, -4, -4, 27 );
			ac = new AddonComponent( 204 );
			AddComponent( ac, -4, -4, 7 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, -4, -3, 33 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, -4, -3, 30 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, -4, -3, 27 );
			ac = new AddonComponent( 201 );
			AddComponent( ac, -4, -3, 7 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, -4, -2, 33 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, -4, -2, 30 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, -4, -2, 27 );
			ac = new AddonComponent( 201 );
			AddComponent( ac, -4, -2, 7 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, -4, -1, 33 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, -4, -1, 30 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, -4, -1, 27 );
			ac = new AddonComponent( 201 );
			AddComponent( ac, -4, -1, 7 );
			ac = new AddonComponent( 201 );
			AddComponent( ac, -4, 1, 7 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, -3, -4, 33 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, -3, -4, 30 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, -3, -4, 27 );
			ac = new AddonComponent( 200 );
			AddComponent( ac, -3, -4, 7 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -3, -3, 22 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -3, -3, 17 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -3, -3, 12 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -3, -3, 7 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -3, -2, 22 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -3, -2, 17 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -3, -2, 12 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -3, -2, 7 );
			ac = new AddonComponent( 2662 );
			AddComponent( ac, -3, -1, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -3, -1, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -3, 0, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -3, 1, 27 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, -2, -4, 33 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, -2, -4, 30 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, -2, -4, 27 );
			ac = new AddonComponent( 200 );
			AddComponent( ac, -2, -4, 7 );
			ac = new AddonComponent( 1846 );
			AddComponent( ac, -2, -3, 22 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -2, -3, 17 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -2, -3, 12 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -2, -3, 7 );
			ac = new AddonComponent( 1846 );
			AddComponent( ac, -2, -2, 22 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -2, -2, 17 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -2, -2, 12 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -2, -2, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -2, -1, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -2, 0, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -2, 1, 27 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, -1, -4, 33 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, -1, -4, 30 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, -1, -4, 27 );
			ac = new AddonComponent( 200 );
			AddComponent( ac, -1, -4, 7 );
			ac = new AddonComponent( 1846 );
			AddComponent( ac, -1, -3, 17 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -1, -3, 12 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -1, -3, 7 );
			ac = new AddonComponent( 1846 );
			AddComponent( ac, -1, -2, 17 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -1, -2, 12 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -1, -2, 7 );
			ac = new AddonComponent( 2662 );
			AddComponent( ac, -1, -1, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -1, -1, 27 );
			ac = new AddonComponent( 2664 );
			AddComponent( ac, -1, 0, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -1, 0, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -1, 1, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -3, 2, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -2, 2, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -1, 2, 27 );
			ac = new AddonComponent( 201 );
			AddComponent( ac, -4, 3, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -3, 3, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -2, 3, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -1, 3, 27 );
			ac = new AddonComponent( 201 );
			AddComponent( ac, -4, 0, 7 );
			ac = new AddonComponent( 2664 );
			AddComponent( ac, -3, 0, 7 );
			ac = new AddonComponent( 201 );
			AddComponent( ac, -4, 2, 7 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, -4, 0, 27 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, -4, 1, 27 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, -4, 2, 27 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, -4, 3, 27 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, -4, 0, 30 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, -4, 1, 30 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, -4, 2, 30 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, -4, 3, 30 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, -4, 0, 33 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, -4, 1, 33 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, -4, 2, 33 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, -4, 3, 33 );
			ac = new AddonComponent( 2664 );
			AddComponent( ac, 1, 0, 7 );
			ac = new AddonComponent( 2664 );
			AddComponent( ac, -3, 3, 7 );
			ac = new AddonComponent( 2664 );
			AddComponent( ac, -1, 3, 7 );
			ac = new AddonComponent( 2664 );
			AddComponent( ac, 1, 3, 7 );
			ac = new AddonComponent( 2662 );
			AddComponent( ac, -3, 2, 7 );
			ac = new AddonComponent( 2662 );
			AddComponent( ac, -1, 2, 7 );
			ac = new AddonComponent( 2662 );
			AddComponent( ac, 1, 2, 7 );
			ac = new AddonComponent( 2662 );
			AddComponent( ac, 1, -1, 7 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, 0, -4, 33 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 0, -4, 30 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 0, -4, 27 );
			ac = new AddonComponent( 202 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 0, -4, 7 );
			ac = new AddonComponent( 1846 );
			AddComponent( ac, 0, -3, 12 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 0, -3, 7 );
			ac = new AddonComponent( 1846 );
			AddComponent( ac, 0, -2, 12 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 0, -2, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 0, -1, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 0, 0, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 0, 1, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 0, 2, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 0, 3, 27 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, 1, -4, 33 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 1, -4, 30 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 1, -4, 27 );
			ac = new AddonComponent( 200 );
			AddComponent( ac, 1, -4, 7 );
			ac = new AddonComponent( 1846 );
			AddComponent( ac, 1, -3, 7 );
			ac = new AddonComponent( 1846 );
			AddComponent( ac, 1, -2, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 1, -1, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 1, 0, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 1, 1, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 1, 2, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 1, 3, 27 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, 2, -4, 33 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 2, -4, 30 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 2, -4, 27 );
			ac = new AddonComponent( 200 );
			AddComponent( ac, 2, -4, 7 );
			ac = new AddonComponent( 5540 );
			AddComponent( ac, 2, -3, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 2, -1, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 2, 0, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 2, 1, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 2, 2, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 2, 3, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -3, 4, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -2, 4, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -1, 4, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 0, 4, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 1, 4, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 2, 4, 7 );
			ac = new AddonComponent( 99 );
			AddComponent( ac, 2, 4, 0 );
			ac = new AddonComponent( 99 );
			AddComponent( ac, 1, 4, 0 );
			ac = new AddonComponent( 99 );
			AddComponent( ac, 0, 4, 0 );
			ac = new AddonComponent( 99 );
			AddComponent( ac, -1, 4, 0 );
			ac = new AddonComponent( 99 );
			AddComponent( ac, -2, 4, 0 );
			ac = new AddonComponent( 99 );
			AddComponent( ac, -3, 4, 0 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, -3, 4, 33 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, -3, 4, 30 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, -3, 4, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -3, 4, 27 );
			ac = new AddonComponent( 200 );
			AddComponent( ac, -3, 4, 7 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, -2, 4, 33 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, -2, 4, 30 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, -2, 4, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -2, 4, 27 );
			ac = new AddonComponent( 200 );
			AddComponent( ac, -2, 4, 7 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, -1, 4, 33 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, -1, 4, 30 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, -1, 4, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, -1, 4, 27 );
			ac = new AddonComponent( 200 );
			AddComponent( ac, -1, 4, 7 );
			ac = new AddonComponent( 201 );
			AddComponent( ac, -4, 4, 7 );
			ac = new AddonComponent( 100 );
			AddComponent( ac, -4, 4, 0 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, -4, 4, 27 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, -4, 4, 30 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, -4, 4, 33 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, 0, 4, 33 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 0, 4, 30 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 0, 4, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 0, 4, 27 );
			ac = new AddonComponent( 202 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 0, 4, 7 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, 1, 4, 33 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 1, 4, 30 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 1, 4, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 1, 4, 27 );
			ac = new AddonComponent( 200 );
			AddComponent( ac, 1, 4, 7 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, 2, 4, 33 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 2, 4, 30 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 2, 4, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 2, 4, 27 );
			ac = new AddonComponent( 200 );
			AddComponent( ac, 2, 4, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 3, -2, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 3, -1, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 3, 0, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 3, 1, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 3, 2, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 3, 3, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 4, -2, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 4, -1, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 4, 0, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 4, 1, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 4, 2, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 4, 3, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 5, -2, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 5, -1, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 5, 0, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 5, 1, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 5, 2, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 5, 3, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 6, -2, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 6, -1, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 6, 0, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 6, 1, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 6, 2, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 6, 3, 7 );
			ac = new AddonComponent( 100 );
			AddComponent( ac, 6, 3, 0 );
			ac = new AddonComponent( 1846 );
			AddComponent( ac, 7, 1, 0 );
			ac = new AddonComponent( 100 );
			AddComponent( ac, 6, -2, 0 );
			ac = new AddonComponent( 100 );
			AddComponent( ac, 6, -1, 0 );
			ac = new AddonComponent( 100 );
			AddComponent( ac, 6, 0, 0 );
			ac = new AddonComponent( 100 );
			AddComponent( ac, 6, 1, 0 );
			ac = new AddonComponent( 100 );
			AddComponent( ac, 6, 2, 0 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 6, -3, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 5, -3, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 4, -3, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 3, -3, 7 );
			ac = new AddonComponent( 100 );
			AddComponent( ac, 6, -3, 0 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, 4, -4, 33 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 4, -4, 30 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 4, -4, 27 );
			ac = new AddonComponent( 200 );
			AddComponent( ac, 4, -4, 7 );
			ac = new AddonComponent( 2662 );
			AddComponent( ac, 5, -3, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 4, -3, 27 );
			ac = new AddonComponent( 2664 );
			AddComponent( ac, 5, -2, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 4, -2, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 4, -1, 27 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, 5, -4, 33 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 5, -4, 30 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 5, -4, 27 );
			ac = new AddonComponent( 200 );
			AddComponent( ac, 5, -4, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 5, -3, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 5, -2, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 5, -1, 27 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, 6, -4, 33 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 6, -4, 30 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 6, -4, 27 );
			ac = new AddonComponent( 200 );
			AddComponent( ac, 6, -4, 7 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, 6, -3, 33 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, 6, -3, 30 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, 6, -3, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 6, -3, 27 );
			ac = new AddonComponent( 201 );
			AddComponent( ac, 6, -3, 7 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, 6, -2, 33 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, 6, -2, 30 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, 6, -2, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 6, -2, 27 );
			ac = new AddonComponent( 203 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 6, -2, 7 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, 6, -1, 33 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, 6, -1, 30 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, 6, -1, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 6, -1, 27 );
			ac = new AddonComponent( 201 );
			AddComponent( ac, 6, 2, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 4, 0, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 5, 0, 27 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, 6, 0, 33 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, 6, 0, 30 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, 6, 0, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 6, 0, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 4, 1, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 5, 1, 27 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, 6, 1, 33 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, 6, 1, 30 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, 6, 1, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 6, 1, 27 );
			ac = new AddonComponent( 98 );
			AddComponent( ac, 6, -4, 0 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 4, 2, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 5, 2, 27 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, 6, 2, 33 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, 6, 2, 30 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, 6, 2, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 6, 2, 27 );
			ac = new AddonComponent( 201 );
			AddComponent( ac, 6, -1, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 4, 3, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 5, 3, 27 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, 6, 3, 33 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, 6, 3, 30 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, 6, 3, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 6, 3, 27 );
			ac = new AddonComponent( 203 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 6, 3, 7 );
			ac = new AddonComponent( 1846 );
			AddComponent( ac, 7, 0, 0 );
			ac = new AddonComponent( 2664 );
			AddComponent( ac, 3, -2, 7 );
			ac = new AddonComponent( 2664 );
			AddComponent( ac, 3, 3, 7 );
			ac = new AddonComponent( 2664 );
			AddComponent( ac, 5, 3, 7 );
			ac = new AddonComponent( 2662 );
			AddComponent( ac, 3, -3, 7 );
			ac = new AddonComponent( 2662 );
			AddComponent( ac, 3, 2, 7 );
			ac = new AddonComponent( 2662 );
			AddComponent( ac, 5, 2, 7 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, 3, -4, 33 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 3, -4, 30 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 3, -4, 27 );
			ac = new AddonComponent( 202 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 3, -4, 7 );
			ac = new AddonComponent( 5541 );
			AddComponent( ac, 3, -3, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 3, -3, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 3, -2, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 3, -1, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 3, 0, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 3, 1, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 3, 2, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 3, 3, 27 );
			ac = new AddonComponent( 2973 );
			AddComponent( ac, 7, -3, 0 );
			ac = new AddonComponent( 1846 );
			AddComponent( ac, 7, -1, 0 );
			ac = new AddonComponent( 1846 );
			AddComponent( ac, 7, 2, 0 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 3, 4, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 4, 4, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 5, 4, 7 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 6, 4, 7 );
			ac = new AddonComponent( 101 );
			AddComponent( ac, 6, 4, 0 );
			ac = new AddonComponent( 99 );
			AddComponent( ac, 4, 4, 0 );
			ac = new AddonComponent( 99 );
			AddComponent( ac, 5, 4, 0 );
			ac = new AddonComponent( 99 );
			AddComponent( ac, 3, 4, 0 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, 4, 4, 33 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 4, 4, 30 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 4, 4, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 4, 4, 27 );
			ac = new AddonComponent( 200 );
			AddComponent( ac, 4, 4, 7 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, 5, 4, 33 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 5, 4, 30 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 5, 4, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 5, 4, 27 );
			ac = new AddonComponent( 200 );
			AddComponent( ac, 5, 4, 7 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, 6, 4, 33 );
			ac = new AddonComponent( 220 );
			AddComponent( ac, 6, 4, 30 );
			ac = new AddonComponent( 220 );
			AddComponent( ac, 6, 4, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 6, 4, 27 );
			ac = new AddonComponent( 199 );
			AddComponent( ac, 6, 4, 7 );
			ac = new AddonComponent( 223 );
			AddComponent( ac, 3, 4, 33 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 3, 4, 30 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 3, 4, 27 );
			ac = new AddonComponent( 1310 );
			AddComponent( ac, 3, 4, 27 );
			ac = new AddonComponent( 202 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 3, 4, 7 );

		}
  
                /*public override void OnAfterDelete()
		{
                     Point3D p = new Point3D( this.X, this.Y, this.Z );
                     Region r = Region.Find( p, this.Map );
                     PlayerCityRegion cityreg = r as PlayerCityRegion;

                     if ( r.IsPartOf( typeof( PlayerCityRegion )))
                      {
                                foreach ( Item i in World.Items.Values )
				{

					if ( i != null && i is CityManagementStone )
					{
						CityManagementStone s = (CityManagementStone)i;
						if ( s.toDelete != null && s.toDelete.Contains( this ) )
                                                {
                                                 s.toDelete.Remove( this );
                                                }

					}
                                        else if ( i != null && i is CivicSign )
					{
						CivicSign t = (CivicSign)i;
      
						if ( t.toDelete != null && t.toDelete.Contains( this ) )
                                                {
                                                 t.toDelete.Remove( this );
                                                 t.Delete();
                                                }

					}
				}
                      }
                      else
                      {
                      return;
                      }
  
			base.OnAfterDelete();
		}*/
              /*public override void OnDestroyed()
		{
		          Container chest = AttachedTo as Container;
                       Point3D p = new Point3D( this.X, this.Y, this.Z );
                       Region r = Region.Find( p, this.Map );
                       PlayerCityRegion cityreg = r as PlayerCityRegion;

                     if ( r.IsPartOf( typeof( PlayerCityRegion )))
                      {
                                foreach ( Item i in World.Items.Values )
				{

					if ( i != null && i is CityManagementStone )
					{
						CityManagementStone s = (CityManagementStone)i;
						if ( s.toDelete != null && s.toDelete.Contains( this ) )
                                                {
                                                 s.toDelete.Remove( this );
                                                }

					}
                                        else if (  i != null && i is CivicSign )
					{
						CivicSign t = (CivicSign)i;
						if ( t.toDelete != null && t.toDelete.Contains( this ) )
                                                {
                                                 t.toDelete.Remove( this );
                                                 t.Delete();
                                                }

					}
				}
                      }*/
			/*if (chest != null && chest.Map != null && chest.Map != Map.Internal)
			{
				ArrayList movelist = new ArrayList(chest.Items);

				foreach (Item i in movelist)
				{
					// spill the contents out onto the ground
					i.MoveToWorld(chest.Location, chest.Map);
				}

				// and permanently destroy the container
				chest.Delete();
			}*/
		//}
                /*public override void OnDelete()
		{
                       Point3D p = new Point3D( this.X, this.Y, this.Z );
                       Region r = Region.Find( p, this.Map );
                       PlayerCityRegion cityreg = r as PlayerCityRegion;

                     if ( r.IsPartOf( typeof( PlayerCityRegion )))
                      {
                                foreach ( Item i in World.Items.Values )
				{

					if ( i != null && i is CityManagementStone )
					{
						CityManagementStone s = (CityManagementStone)i;
						if ( s.toDelete != null && s.toDelete.Contains( this ) )
                                                {
                                                 s.toDelete.Remove( this );
                                                }

					}
                                        else if (  i != null && i is CivicSign )
					{
						CivicSign t = (CivicSign)i;
						if ( t.toDelete != null && t.toDelete.Contains( this ) )
                                                {
                                                 t.toDelete.Remove( this );
                                                 t.Delete();
                                                }

					}
				}
                      }
                      else
                      {
                      return;
                      }
			               base.OnDelete();
		}*/
		public BarracksAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	/*public class BarracksAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new BarracksAddon();
			}
		}

		[Constructable]
		public BarracksAddonDeed()
		{
			Name = "Barracks";
		}

		public BarracksAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}*/
}
